FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 2000
EXPOSE 3443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "localisation.csproj"
RUN dotnet publish "localisation.csproj" -c Release -o /app/publish -r linux-x64 --self-contained false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY ./wwwroot ./wwwroot
ENTRYPOINT ["dotnet", "localisation.dll"]