FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["./localisation.csproj", "localisation/"]
RUN dotnet restore "localisation/localisation.csproj"
COPY . .
RUN dotnet build "localisation.csproj" -c Release -o /app/build -r linux-x64

# FROM build AS publish
# RUN dotnet publish "localisation.csproj" -c Release -o /app/publish -r linux-x64

FROM base AS final

WORKDIR /app
COPY --from=build /app/build .
COPY ./wwwroot ./wwwroot
ENTRYPOINT ["dotnet", "localisation.dll"]